# Generated by Django 5.1.1 on 2025-01-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hobby_popularity_user_friends_notification_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageView',
        ),
    ]
